default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chat_development
  username: evgenos
  password: 1111

test:
  <<: *default
  database: chat_test
  username: evgenos
  password: 1111

production:
  <<: *default
  database: chat_production
  username: chat
  password: <%= ENV['CHAT_DATABASE_PASSWORD'] %>
